"""initial_schema

Revision ID: 2302045872a7
Revises: 
Create Date: 2026-06-20 23:57:31.402878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2302045872a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hours_per_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived', 'completed', 'generating', 'failed')", name='ck_status_valid'),
    sa.CheckConstraint('hours_per_day >= 1 AND hours_per_day <= 8', name='ck_hours_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plans_created_at', 'plans', ['created_at'], unique=False)
    op.create_index('idx_plans_status', 'plans', ['status'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'name', name='uq_concept_plan_name')
    )
    op.create_index('idx_concepts_plan_id', 'concepts', ['plan_id'], unique=False)
    op.create_table('concept_content',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('quiz', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id')
    )
    op.create_index('idx_content_concept_id', 'concept_content', ['concept_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('from_concept_id', sa.UUID(), nullable=False),
    sa.Column('to_concept_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_concept_id != to_concept_id', name='ck_no_self_loop'),
    sa.ForeignKeyConstraint(['from_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'from_concept_id', 'to_concept_id', name='uq_edge_unique')
    )
    op.create_index('idx_edges_from', 'edges', ['from_concept_id'], unique=False)
    op.create_index('idx_edges_plan_id', 'edges', ['plan_id'], unique=False)
    op.create_index('idx_edges_to', 'edges', ['to_concept_id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('untouched', 'learned', 'struggling', 'skipped')", name='ck_progress_status'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'concept_id', name='uq_progress_plan_concept')
    )
    op.create_index('idx_progress_plan_concept', 'progress', ['plan_id', 'concept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_progress_plan_concept', table_name='progress')
    op.drop_table('progress')
    op.drop_index('idx_edges_to', table_name='edges')
    op.drop_index('idx_edges_plan_id', table_name='edges')
    op.drop_index('idx_edges_from', table_name='edges')
    op.drop_table('edges')
    op.drop_index('idx_content_concept_id', table_name='concept_content')
    op.drop_table('concept_content')
    op.drop_index('idx_concepts_plan_id', table_name='concepts')
    op.drop_table('concepts')
    op.drop_index('idx_plans_status', table_name='plans')
    op.drop_index('idx_plans_created_at', table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
