"""add_calendar_timetable

Revision ID: 26763c8804bc
Revises: 3ad1291ced5a
Create Date: 2026-07-04 02:27:47.874726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26763c8804bc'
down_revision: Union[str, Sequence[str], None] = '3ad1291ced5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('calendar_timetable', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'calendar_timetable')
    # ### end Alembic commands ###
