"""add_final_plan_layer_columns

Revision ID: 28b3c30d419f
Revises: fd8a5528ef1a
Create Date: 2026-06-30 10:17:10.724047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28b3c30d419f'
down_revision: Union[str, Sequence[str], None] = 'fd8a5528ef1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('selected_option_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('confidence_reported', sa.Float(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_attempts_concept_id', 'quiz_attempts', ['concept_id'], unique=False)
    op.create_index('idx_quiz_attempts_plan_id', 'quiz_attempts', ['plan_id'], unique=False)
    op.add_column('concepts', sa.Column('difficulty', sa.String(length=50), nullable=False, server_default='medium'))
    op.add_column('concepts', sa.Column('difficulty_source', sa.String(length=50), nullable=False, server_default='llm_assigned'))
    op.add_column('concepts', sa.Column('content_generation_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('concepts', sa.Column('source_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('concepts', sa.Column('is_inferred_reading', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('concepts', sa.Column('recommended_reading', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('edges', sa.Column('confidence', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('edges', sa.Column('source', sa.String(length=50), nullable=False, server_default='llm_inferred'))
    op.add_column('plans', sa.Column('subject_domain', sa.String(length=200), nullable=True))
    op.add_column('plans', sa.Column('source_books', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('plans', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('progress', sa.Column('mastery_pct', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('progress', sa.Column('retention_pct', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('progress', sa.Column('confidence_level', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('progress', sa.Column('attempts_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('progress', sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress', 'last_reviewed_at')
    op.drop_column('progress', 'attempts_count')
    op.drop_column('progress', 'confidence_level')
    op.drop_column('progress', 'retention_pct')
    op.drop_column('progress', 'mastery_pct')
    op.drop_column('plans', 'raw_text')
    op.drop_column('plans', 'source_books')
    op.drop_column('plans', 'subject_domain')
    op.drop_column('edges', 'source')
    op.drop_column('edges', 'confidence')
    op.drop_column('concepts', 'recommended_reading')
    op.drop_column('concepts', 'is_inferred_reading')
    op.drop_column('concepts', 'source_hint')
    op.drop_column('concepts', 'content_generation_version')
    op.drop_column('concepts', 'difficulty_source')
    op.drop_column('concepts', 'difficulty')
    op.drop_index('idx_quiz_attempts_plan_id', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_concept_id', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
