"""add_is_flagged_to_quiz_attempts

Revision ID: 3ad1291ced5a
Revises: 5ced83f5c026
Create Date: 2026-07-01 01:00:05.648909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad1291ced5a'
down_revision: Union[str, Sequence[str], None] = '5ced83f5c026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('is_flagged', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'is_flagged')
    # ### end Alembic commands ###
