"""add_schedule_table

Revision ID: 411440a59620
Revises: 2302045872a7
Create Date: 2026-06-21 00:12:43.292733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411440a59620'
down_revision: Union[str, Sequence[str], None] = '2302045872a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.CheckConstraint("priority IN ('high', 'medium', 'low')", name='ck_schedule_priority'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'concept_id', name='uq_schedule_plan_concept')
    )
    op.create_index('idx_schedule_plan_id', 'schedule', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_schedule_plan_id', table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
