"""add_srs_fields_to_progress

Revision ID: 9f370f468b06
Revises: f4c273ba9448
Create Date: 2026-06-22 16:15:30.482803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f370f468b06'
down_revision: Union[str, Sequence[str], None] = 'f4c273ba9448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('progress', sa.Column('interval_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('progress', sa.Column('ease_factor', sa.Float(), nullable=False, server_default='2.5'))
    op.add_column('progress', sa.Column('repetitions', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('idx_progress_next_review', 'progress', ['next_review_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_progress_next_review', table_name='progress')
    op.drop_column('progress', 'repetitions')
    op.drop_column('progress', 'ease_factor')
    op.drop_column('progress', 'interval_days')
    op.drop_column('progress', 'next_review_at')
    # ### end Alembic commands ###
