"""add_clerk_user_id_to_plans

Revision ID: a007d0cc3a33
Revises: 411440a59620
Create Date: 2026-06-22 16:05:09.607924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a007d0cc3a33'
down_revision: Union[str, Sequence[str], None] = '411440a59620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('clerk_user_id', sa.String(length=128), nullable=True))
    op.create_index('idx_plans_clerk_user_id', 'plans', ['clerk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_plans_clerk_user_id', table_name='plans')
    op.drop_column('plans', 'clerk_user_id')
    # ### end Alembic commands ###
