import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth, useClerk } from '@clerk/clerk-react'
import { getLibrary, forkPlan } from '../api/client'
import type { LibraryPlanItem } from '../types'

export default function CommunityLibrary() {
  const { getToken, isSignedIn, isLoaded } = useAuth()
  const { openSignIn } = useClerk()
  const navigate = useNavigate()

  const [plans, setPlans] = useState<LibraryPlanItem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [searchQuery, setSearchQuery] = useState('')
  const [sortOrder, setSortOrder] = useState<'newest' | 'oldest'>('newest')
  const [forkingId, setForkingId] = useState<string | null>(null)

  const fetchLibrary = async () => {
    try {
      setLoading(true)
      // Pass token if signed in (optional for library, but good for backend tracking if desired)
      const token = isSignedIn ? await getToken() : null
      const data = await getLibrary(searchQuery, sortOrder, 50, 0, token)
      setPlans(data)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load library')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (!isLoaded) return
    fetchLibrary()
  }, [isLoaded, sortOrder, searchQuery])

  const handleFork = async (e: React.MouseEvent, planId: string) => {
    e.preventDefault()
    e.stopPropagation()

    if (!isSignedIn) {
      openSignIn({ redirectUrl: '/library' })
      return
    }

    try {
      setForkingId(planId)
      const token = await getToken()
      if (token) {
        const res = await forkPlan(planId, token)
        navigate(`/plan/${res.new_plan_id}`)
      }
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to fork plan')
    } finally {
      setForkingId(null)
    }
  }

  return (
    <div className="relative min-h-[80vh]">
      {/* Ambient gradient backgrounds */}
      <div className="absolute -top-20 -left-20 w-80 h-80 bg-violet-600/10 rounded-full blur-[90px]" />
      <div className="absolute -bottom-20 -right-20 w-80 h-80 bg-fuchsia-600/10 rounded-full blur-[90px]" />

      <div className="relative z-10 space-y-8">
        {/* Page Header */}
        <div className="text-center max-w-2xl mx-auto space-y-3">
          <h1 className="text-4xl font-extrabold tracking-tight text-white bg-clip-text bg-gradient-to-r from-violet-200 via-indigo-100 to-fuchsia-200">
            Community Library
          </h1>
          <p className="text-slate-400 text-sm md:text-base">
            Explore public learning paths generated by the community. Fork any curriculum to customize, track progress, and study with the AI tutor.
          </p>
        </div>

        {/* Search & Sort Panel */}
        <div className="flex flex-col sm:flex-row gap-4 justify-between items-center bg-slate-900/30 border border-slate-900 p-4 rounded-2xl backdrop-blur-md">
          {/* Search Input */}
          <div className="relative w-full sm:max-w-md">
            <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-slate-500">
              🔍
            </span>
            <input
              type="text"
              placeholder="Search library topics..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 text-sm bg-slate-950/80 border border-slate-800 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:border-violet-500 transition duration-200"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="absolute inset-y-0 right-0 pr-3 flex items-center text-slate-500 hover:text-white"
              >
                ✕
              </button>
            )}
          </div>

          {/* Sort Dropdown */}
          <div className="flex items-center gap-3 w-full sm:w-auto justify-end">
            <span className="text-xs text-slate-400 font-medium">Sort By:</span>
            <select
              value={sortOrder}
              onChange={(e) => setSortOrder(e.target.value as 'newest' | 'oldest')}
              className="bg-slate-950/80 border border-slate-800 rounded-xl px-3 py-2 text-xs font-semibold text-slate-200 focus:outline-none focus:border-violet-500 cursor-pointer"
            >
              <option value="newest">Newest First</option>
              <option value="oldest">Oldest First</option>
            </select>
          </div>
        </div>

        {/* Error Alert */}
        {error && (
          <div className="p-4 rounded-xl border border-rose-500/20 bg-rose-500/10 text-rose-300 text-sm">
            ⚠️ {error}
          </div>
        )}

        {/* Loading Spinner */}
        {loading ? (
          <div className="flex flex-col items-center justify-center py-24">
            <div className="w-12 h-12 border-4 border-violet-500/20 border-t-violet-500 rounded-full animate-spin mb-4" />
            <p className="text-slate-400 text-sm animate-pulse">Browsing public curricula...</p>
          </div>
        ) : plans.length === 0 ? (
          /* Empty State */
          <div className="text-center py-20 bg-slate-900/10 border border-dashed border-slate-800 rounded-3xl p-8">
            <span className="text-5xl block mb-4">🔮</span>
            <h3 className="text-lg font-bold text-white mb-2">No Plans Found</h3>
            <p className="text-slate-400 text-sm max-w-sm mx-auto">
              {searchQuery
                ? `No public plans matched "${searchQuery}". Try searching for something else.`
                : 'The library is currently empty. Be the first to publish a plan!'}
            </p>
          </div>
        ) : (
          /* Library Grid */
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {plans.map((plan) => (
              <div
                key={plan.id}
                className="group flex flex-col justify-between p-6 rounded-2xl border border-slate-900 bg-slate-900/30 hover:bg-slate-900/60 hover:border-violet-500/35 transition duration-300 shadow-md backdrop-blur-sm"
              >
                <div className="space-y-4">
                  <div className="flex items-start justify-between gap-2">
                    <h3 className="font-bold text-white group-hover:text-violet-400 transition text-lg leading-tight line-clamp-2">
                      {plan.topic}
                    </h3>
                  </div>

                  <div className="space-y-1.5 text-xs text-slate-400">
                    <div className="flex justify-between">
                      <span>Concepts:</span>
                      <span className="text-slate-200 font-semibold">{plan.concept_count} nodes</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Study Pacing:</span>
                      <span className="text-slate-200 font-semibold">{plan.hours_per_day}h / day</span>
                    </div>
                    {plan.exam_date && (
                      <div className="flex justify-between">
                        <span>Exam Date:</span>
                        <span className="text-slate-200 font-semibold">
                          {new Date(plan.exam_date).toLocaleDateString(undefined, {
                            year: 'numeric',
                            month: 'short',
                            day: 'numeric',
                          })}
                        </span>
                      </div>
                    )}
                    <div className="flex justify-between">
                      <span>Published:</span>
                      <span className="text-slate-500">
                        {new Date(plan.created_at).toLocaleDateString()}
                      </span>
                    </div>
                  </div>
                </div>

                <div className="mt-6 pt-4 border-t border-slate-900/80 flex items-center justify-between">
                  <span className="text-[10px] text-slate-500 font-mono select-all">
                    ID: {plan.id.slice(0, 8)}...
                  </span>
                  
                  <button
                    onClick={(e) => handleFork(e, plan.id)}
                    disabled={forkingId === plan.id}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-violet-600 hover:bg-violet-500 disabled:bg-violet-700/50 text-white font-semibold text-xs rounded-lg transition duration-200 shadow-sm"
                  >
                    {forkingId === plan.id ? (
                      <>
                        <div className="w-3.5 h-3.5 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                        <span>Forking...</span>
                      </>
                    ) : (
                      <>
                        <span>🍴</span>
                        <span>Fork Plan</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
